---
 - name: Realizando apt-get update
   apt:
    update_cache: yes

 - name: Modificando Hostname
   shell: hostname {{ inventory_hostname }}

 - name: Instalando a versão mais recente do Docker
   #shell: curl -sS https://get.docker.com | sh
   apt:
    name: docker.io
    update-cache: yes

 - name: Reiniciar o servico do Docker
   systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: docker
